### ISSUE TITLE
consider update the peer max limit to Uint32?

### ISSUE THREAD

**Issue by ryanxia2016** [nxrighthere/ENet-CSharp#10]
finally I run ENet-Charp successfuly.

seemed the performance is good, 4000 concurrent clients keep sending/receiving messages(256 bytes per message, 50k messages per second)

Server CPU Usage is around 30% (Intel i7 7820X)

then, should we do something with the 4096 peer max limit?

yes, it will break the enet protocol compatibly

but, as a new version, it's a chance to do something.  is't it ? 

once the lib is used widely, then it's difficult to do such things.

and, such modification seemed easy

https://github.com/BeRo1985/enet/commit/75344d13bf4b94b784c7a1b5c9e42487a6320e1a

https://github.com/BeRo1985/enet/commit/28ef9e213114a5376e4198d8d4d4cd938fb7e9a4

**Comment by nxrighthere** [comment]
In a real-world application, this number of peers is more than enough for a single server instance. The bottleneck is usually not the CPU, but the NIC.

Using a single server that will deal with 4000 peers will not lead to anything good. So no, this limit will not be touched.

Small server instances is a way to distribute the workload and prevent issues with latency, even if the server is just a proxy for synchronization of network entities.

**Comment by ryanxia2016** [comment]
our gateway server in Production has 96 CPU cores and 384G RAM

so if one host only provide 4000 peers,  maybe need more then 20 host instances , it's expensive to manage.

enet protocol is designed many years ago, so the change maybe a considerable point.

**Comment by nxrighthere** [comment]
What's the problem to modify the library to go beyond this limit, since you know what changes should be made? 🙂

**Comment by ryanxia2016** [comment]
yes it's not difficult to maintenance "another-version"
 
after followed your benchmark project for almost half year
I like your project, and hope your new enet based lib can be used more widely
