### ISSUE TITLE
Question about PacketFlags

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#15]
Is PacketFlags.Unsequenced reliable? Not sure if that is the correct word. I guess a better way of saying it; Are the packets resent to try to guarantee delivery?

I noticed it says 

> PacketFlags.None unreliable sequenced, delivery of packet is not guaranteed.
> PacketFlags.Unsequenced a packet will not be sequenced with other packets and may be delivered out of order.

but not sure if that means it is guaranteed delivery? Or is it kinda like a less reliable version `PacketFlags.None`?

Right now I am using `PacketFlags.Unsequenced` in parts where I do not need it to arrive in order but I need it to be delivered. If this is not how it works I can always switch to `PacketFlags.Reliable`. 
Thanks :).

Extra questions out of curiosity:
1. Is `PacketFlag.None` the defualt one if parameter is left blank?
2. Could you give me simple example of when I would use`PacketFlags.NoAllocate` and `PacketFlags.UnreliableFragment`?

Extra thanks!

**Comment by nxrighthere** [comment]
Delivery of the packet is not guaranteed until `PacketFlags.Reliable` is specified.

> Right now I am using PacketFlags.Unsequenced in parts where I do not need it to arrive in order but I need it to be delivered.

If you want to make it reliable unsequenced, then you can set multiple flags:
`packet.Create(data, data.Length, PacketFlags.Reliable | PacketFlags.Unsequenced);`

> Is PacketFlag.None the defualt one if parameter is left blank?

If none of the flags is specified, then the packet will be sent as unreliable sequenced by default.

> Could you give me simple example of when I would usePacketFlags.NoAllocate and PacketFlags.UnreliableFragment?

When `PacketFlags.NoAllocate` is set, ENet will not allocate memory for the packet data, and the pointer to the buffer will be used instead, which means that you should take care of its lifetime.

`PacketFlags.UnreliableFragment` can be used for stuff like chat messages or logs where the packet may exceed the MTU to avoid fragmentation at the IP level.
