### ISSUE TITLE
Is it compatible with a server that runs on original enet C library?

### ISSUE THREAD

**Issue by edoaxyz** [nxrighthere/ENet-CSharp#16]
I tried several times to connect to a server based on the original enet C library via android using a shared library built with Android-NDK but every time I try to connect it disconnect after a while without giving any error or some return code.
I checked also if the client was able to contact the server, so I used wireshark for analysing network packets and I confirmed that the client was able to contact it because some UDP packets were sent both by client and server.

**Comment by nxrighthere** [comment]
No, it's not compatible. This version is heavily modified. Many legacy things were removed/replaced.
