### ISSUE TITLE
Setting more than 255 channels in Host.Create or Host.Connect causes crash

### ISSUE THREAD

**Issue by Narcotic904** [nxrighthere/ENet-CSharp#19]
The parameter should take a byte instead of int.

**Comment by nxrighthere** [comment]
[This](https://github.com/nxrighthere/ENet-CSharp/blob/master/Source/Managed/ENet.cs#L401) function will not allow you to create a host with more than 255 channels an exception will be thrown.

**Comment by nxrighthere** [comment]
`host.Create(address, maxClients, 256);` throws `ArgumentOutOfRangeException` for me.

**Comment by nxrighthere** [comment]
Make sure that you handle exceptions in your program in the right way.
