### ISSUE TITLE
(Server)Disconnect All

### ISSUE THREAD

**Issue by Avatarchik** [nxrighthere/ENet-CSharp#21]
Hi! When I turn off the server, I can send a disconnect to all the clients so that they are not disconnected by any means, but when the server is turned off

**Comment by nxrighthere** [comment]
You just track each connected peer in an array or dictionary and then iterate through it calling `peers[i].Disconnect((uint)Reason.Shutdown)` for each. If you are disconnecting peers when the service function is no longer in a loop, then you must call `Host.Flush();` to send the disconnect command to them.
