### ISSUE TITLE
IPv6 Support and improvements from original Enet C library

### ISSUE THREAD

**Issue by sofmz** [nxrighthere/ENet-CSharp#22]
As far as I know original Enet has no IPv6 support(although there are few Enet C library forks around have added IPv6 support)

Apart from added IPv6 support, is there a list of few notable modification/improvement from original Enet library? I think that will be useful for users that have experience in using original Enet. 

Thanks for the great works!

**Comment by nxrighthere** [comment]
> Apart from added IPv6 support, is there a list of few notable modification/improvement from original Enet library?

Sure, the most notable changes:

- Added functionality for easier bindings
- Added monotonic time
- Improved connection-related calculations
- Improved compatibility with various compilers
- Improved transmission statistics
- Eliminated unnecessary memory allocations
- Removed/replaced legacy functionality
- Combined code base into a single header
- Cleaned and reorganized code base

> Thanks for the great works!

You welcome!

**Comment by nxrighthere** [comment]
[Added](https://github.com/nxrighthere/ENet-CSharp/commit/5dd36be3f57ce0f7355b3f1e41b5724ff9169b6e) packet-level LZ4 compression. It works especially well when multiple packets are combined into one for a particular peer. In my tests ~100 mbps upstream bandwidth down to ~80 mbps. To enable compression just call `enet_host_enable_compression()` with the native library or `Host.EnableCompression()` with the managed after a host is created.

**Comment by patrickspam31** [comment]
great

**Comment by nxrighthere** [comment]
[Implemented](https://github.com/nxrighthere/ENet-CSharp/commit/e5f8bc0f669e0312ee5874286dad57f968a2b9f4) round-trip time calculation based on [Jacobson’s algorithm](https://www.netlab.tkk.fi/opetus/s383141/kalvot/E_tcp_flc.pdf) to achieve smooth and precise values. So you will see 1 ms on a local machine as it should be, and even under lag simulation, round-trip time values will be precise and smooth.

**Comment by nxrighthere** [comment]
You can track all other changes since 2.1.3 version (when SRTT was implemented) in the [release](https://github.com/nxrighthere/ENet-CSharp/releases) section.
