### ISSUE TITLE
Android NDK Build Failed 

### ISSUE THREAD

**Issue by patrickspam31** [nxrighthere/ENet-CSharp#23]
Build command failed.
Error while executing process E:\Programs_Files\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\SADIKI\AndroidStudioProjects\EnetLibrary\app\.externalNativeBuild\cmake\debug\mips --target native-lib}
[1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\mips\libnative-lib.so
FAILED: cmd.exe /C "cd . && E:\Programs_Files\android-ndk-r13b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  -target mipsel-none-linux-android -gcc-toolchain E:/Programs_Files/android-ndk-r13b/toolchains/mipsel-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=E:/Programs_Files/android-ndk-r13b/platforms/android-15/arch-mips -fPIC -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mips32 -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -std=c++14 -fexceptions -O0 -fno-limit-debug-info  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\mips\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/library.cpp.o  -llog -lm "E:/Programs_Files/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libgnustl_static.a" && cd ."
CMakeFiles/native-lib.dir/src/main/cpp/library.cpp.o: In function `enet_time_get':
C:\Users\SADIKI\AndroidStudioProjects\EnetLibrary\app\src\main\cpp/enet.h:4383: undefined reference to `__atomic_load_8'
C:\Users\SADIKI\AndroidStudioProjects\EnetLibrary\app\src\main\cpp/enet.h:4387: undefined reference to `__atomic_compare_exchange_8'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by nxrighthere** [comment]
I tried the latest NDK version, and everything works without any problems.

![android_build](https://user-images.githubusercontent.com/8279330/47602350-14910d00-d9f7-11e8-88ce-efbf5a531619.PNG)

How do you build?

**Comment by patrickspam31** [comment]
thanks i'll try currently ndk r13b does not compile x86 mips and armabi the others ABI compile just fine

**Comment by patrickspam31** [comment]
> Make sure that you are using r14 version or higher. The files for building the library are in the _jni_ folder.

I was trying with Android Studio then i leave it for directly compile with ndk-build command

**Comment by patrickspam31** [comment]
> I tried the latest NDK version, and everything works without any problems.
> 
> ![android_build](https://user-images.githubusercontent.com/8279330/47602350-14910d00-d9f7-11e8-88ce-efbf5a531619.PNG)
> 
> How do you build?

I was trying with Android Studio then i leave it for directly compile with ndk-build command

**Comment by nxrighthere** [comment]
So, can you confirm that the r14 is working fine?

**Comment by patrickspam31** [comment]
Sorry i was a bit busy. it's works with r16b

**Comment by nxrighthere** [comment]
No problem. Glad to hear that.
