### ISSUE TITLE
Mac OSX - Server not receiving Connect event 

### ISSUE THREAD

**Issue by philwinkel** [nxrighthere/ENet-CSharp#24]
I'm having issues getting ENet to work on Mac OSX. The server never seems to receive the Connect event when the client is connecting. The client PeerState says its connecting. I am testing in the editor, where the client is connecting to localhost server running in the same unity instance.

I am on Mac OSX Mojave , 10.14. Works fine on windows. I have attached a sample project in which i reproduced the bug. This bug occurs using both Unity 2018.3.0b7 (beta) as well as 2018.2.14f1 (latest stable). If there's anything else i can do to help let me know. Thanks

[enet-mac-issue.zip](https://github.com/nxrighthere/ENet-CSharp/files/2530791/enet-mac-issue.zip)

**Comment by nxrighthere** [comment]
That's strange. A guy a few days ago reported that it works fine on macOS 10.13.6. I'll investigate this.

**Comment by nxrighthere** [comment]
Tell me please scripting runtime version and backend that you are using in Unity.

**Comment by philwinkel** [comment]
In my repro project i attached, i was using:
- Scripting Runtime Version: .NET 3.5 equivalent
- Scripting Backend: Mono

I just tried changing it to the following configs, and each had same results. 
- .NET 3.5 equivalent, IL2CPP
- .NET 4x equivalent , Mono
- .NET 4x , IL2CPP

**Comment by nxrighthere** [comment]
I'm a bit confused actually. It doesn't work even on Windows for me, but I don't see any mistakes in the code. Packets have reached the server, but the client is stuck at the connection stage. You are trying to establish a connection with the server and client using them both in the same Unity process, right? I'm going to split them.

**Comment by nxrighthere** [comment]
Okay, you forgot to replace `Console.WriteLine` with `Debug.Log`, so fix this and check how it works. 😃

**Comment by philwinkel** [comment]
oh man, my bad!! i put together the sample in kind of a rush.  The sample is working for me after I made that change. I'll have to dig deeper in my real project and see whats going on, must be something else. Sorry for wasting your time on this!!

**Comment by nxrighthere** [comment]
No problem. Glad to hear that. 😸
