### ISSUE TITLE
Client IP is not complete value?

### ISSUE THREAD

**Issue by wobes1** [nxrighthere/ENet-CSharp#25]
Hello.

First of all, I would like to thank you for the wrapper and the work that you have done.
It seems like netEvent.Peer.IP doesn't return a complete value?
See screenshot below:
https://i.imgur.com/hANeEx9.png

Thank you.

**Comment by nxrighthere** [comment]
That's strange. Tell me please what operating system you running on/scripting backend?

**Comment by wobes1** [comment]
OS: Windows 10 x64
Backend: Mono
Runtime Version: Net 4.x Equivalent
Packages  installed: Burst, ECS, Incremental Compiler.

And also, a question about multi-threading, if you have a moment.
Would you recommend threading in Unity for ENet? And what would be the best approach for that?

Thank you!

**Comment by nxrighthere** [comment]
> Would you recommend threading in Unity for ENet? And what would be the best approach for that?

One of the solutions is to use a dedicated thread for everything that related to the ENet and its functions. You need something like inter-thread communication where are you calling functions from one thread and they become processed in the another. You can use a disruptor-like [queue](https://github.com/dave-hillier/disruptor-unity3d) and mix it with [buffers pooling](https://adamsitnik.com/Array-Pool/) and friends to minimize GC.

**Comment by wobes1** [comment]
> > Would you recommend threading in Unity for ENet? And what would be the best approach for that?
> 
> One of the solutions is to use a dedicated thread for everything that related to the ENet and its functions. You need something like inter-thread communication where you are calling functions from one thread, and they become processed in the another. You can use a disruptor-like [queue](https://github.com/dave-hillier/disruptor-unity3d) for this and mix it with [buffers pooling](https://adamsitnik.com/Array-Pool/) and friends to minimize GC.

Thank you for that.

**Comment by nxrighthere** [comment]
Thank you for the contribution on Bountysource, I appreciate that.

**Comment by wobes1** [comment]
You are welcome!

Last question, my goal is to achieve handling of 500 realtime connections. Here: https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-miniudp-hazel-photon-and-others.512507/page-6 you have mentioned 2 was. Sync , Async, what would you recommend? 

Serializer would be Google.Protobuf.

**Comment by nxrighthere** [comment]
The first synchronous part actually can be asynchronous as well. I didn't make it asynchronous because all 3 steps are executed very fast in the producer thread (the game loop), and it doesn't involve latency. The biggest consumer of CPU time is serialization which can be parallelized as well.

The second asynchronous part is performed in the thread where ENet is sitting and processing network events. But before calling the service function I processing send/broadcast functions from the inbound queue. Then ENet shuttles packets, processing network events and enqueues inter-thread messages to the outbound queue to send events to the producer thread, but it can by any other (for parallelizing deserialization for example and then pushing message to the game loop).

**Comment by nxrighthere** [comment]
If you have any questions, feel free to ask, I'll try to explain stuff.

**Comment by nxrighthere** [comment]
@wobes1 As for this issue, in ENet.cs try to remove lines 557 and 558, then tell me please what returns `Peer.IP` property.

**Comment by nxrighthere** [comment]
Make sure that this thing which prints logs is parsing them correctly because it seems that it's eating the last numbers of an address for some reason. I can't find a mistake in the code at my end. It should work correctly.

**Comment by wobes1** [comment]
Thank you so much for all of your explanations. It is very useful knowledge. As for the issue, I will get back to it tomorrow and let you know. 


Thank you again.

**Comment by nxrighthere** [comment]
Nevermind, found where's the problem was.

**Comment by wobes1** [comment]
Thank you for quick fix.
