### ISSUE TITLE
Trouble connecting client to server

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#3]
Hi, I was wondering if you have tried to connect a client to the server already. If you did and it worked then that gives me hope that it is something I can fix on my own. 

I am using the usage examples as well as the changes you suggested in my last question. I'm gonna keep troubleshooting this but just thought I would ask just in case.

**Comment by nxrighthere** [comment]
A complex networking backend is built using this project in Unity. I can't say why it's not working for you without looking into your code.

**Comment by bureto** [comment]
Heres the client:
`
     using UnityEngine;
     using ENet;

    public class clientTest : MonoBehaviour
    {
    Host client;
    Peer peer;

    Address address;
    string serverIP = "127.0.0.1";
    ushort port = 40000;


    void Start()
    {
        ENet.Library.Initialize();
        CreateClient();
    }

    private void CreateClient()
    {
        client = new Host();
        address = new Address();

        address.SetHost(serverIP);
        address.Port = port;
        client.Create();
        peer = client.Connect(address);
    }

    private void Update()
    {
        ENet.Event netEvent;
        client.Service(0, out netEvent);
        Debug.Log(peer.State);

        switch (netEvent.Type)
        {
            case ENet.EventType.None:
                Debug.Log("no event occurred within the specified time limit.");
                break;
            case ENet.EventType.Connect:
                Debug.Log("Client connected to server (ID: " + peer.ID + ")");
                break;

            case ENet.EventType.Disconnect:
                Debug.Log("Client disconnected from server");
                break;

            case ENet.EventType.Timeout:
                Debug.Log("Client connection timeout");
                break;

            case ENet.EventType.Receive:
                Debug.Log("Packet received from server (Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length + ")");
                netEvent.Packet.Dispose();
                break;
        }
    }
}

`

**Comment by bureto** [comment]
And here's the server, also I really appreciate you helping me it is crazy how fast you respond :+1: 

`
using UnityEngine;
using ENet;

    public class serverTest : MonoBehaviour {

    Host server;
    Address address;
    ushort port = 40000;
    int maxClients;
    // Use this for initialization
    void Start () {
        ENet.Library.Initialize();
        StartServer();
	}

    private void StartServer()
    {
        server = new Host();
        address = new Address();
        address.Port = port;
        server.Create(address, maxClients);
    }

    private void Update()
    {
        ENet.Event netEvent;
        server.Service(0, out netEvent);
        switch (netEvent.Type)
        {
            case ENet.EventType.None:
                Debug.Log("none");
                break;
            case ENet.EventType.Connect:
                Debug.Log("Client connected (ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.Address.GetIP() + ")");
                break;

            case ENet.EventType.Disconnect:
                Debug.Log("Client disconnected (ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.Address.GetIP() + ")");
                break;

            case ENet.EventType.Timeout:
                Debug.Log("Client timeout (ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.Address.GetIP() + ")");
                break;

            case ENet.EventType.Receive:
                Debug.Log("Packet received from (ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.Address.GetIP() + ", Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length + ")");
                netEvent.Packet.Dispose();
                break;
        }
    }
}
`

**Comment by nxrighthere** [comment]
The first one, you didn't deinitialize the library at the end of the session. Add the following code to your MonoBehaviour class:
```csharp
private void OnDestroy() {
	ENet.Library.Deinitialize();
}
```
And second, you forgot to assign `maxClients` value, so it's zero by default which means that the new connections are not allowed.

Restart the editor after applying these changes.

**Comment by nxrighthere** [comment]
It works fine for me with a limit of 5 or fewer clients, so I guess it's just a temporary issue due to your adventures. 😄

**Comment by bureto** [comment]
Ahh I forgot about `Run In Background`, just checked and it works for me also. :+1:
