### ISSUE TITLE
Null terminated strings from C aren't handled correctly by GetString() in IP()

### ISSUE THREAD

**Issue by NongBenz** [nxrighthere/ENet-CSharp#30]
Null terminated strings from C aren't handled correctly by GetString() in IP(). I have to do...

string safeString = peer.IP;
safeString = safeString.Remove(safeString.IndexOf("\0"));

for things to work correctly again, else Debug.Log("Length: " + peer.IP.Length); will return really long values like 57 and won't match with anything.

public string IP {
			get {
				CheckCreated();

				byte[] ip = ArrayPool.GetBuffer();

				if (Native.enet_peer_get_ip(nativePeer, ip, (IntPtr)ip.Length) == 0) {
					if (Encoding.ASCII.GetString(ip).Remove(7) == "::ffff:")
						return Encoding.ASCII.GetString(ip).Substring(7);

					return Encoding.ASCII.GetString(ip);
				} else {
					return String.Empty;
				}
			}
		}

**Comment by NongBenz** [comment]
Looking at Nate Shoffner's code, think you have to give a length so it doesn't over-run. I'l do some testing.

private static string BytesToString(byte[] bytes)
        {
            try
            {
                return Encoding.ASCII.GetString(bytes, 0, Native.strlen(bytes));
            }
            catch
            {
                return null;
            }
        }

**Comment by NongBenz** [comment]
After some tests, the following changes to ENet.cs (finding the null terminator manually) fixes it.

	 public string IP {
		get {
			CheckCreated();

			byte[] ip = ArrayPool.GetBuffer();

			if (Native.enet_peer_get_ip(nativePeer, ip, (IntPtr)ip.Length) == 0) {
				if (Encoding.ASCII.GetString(ip).Remove(7) == "::ffff:")
					return Encoding.ASCII.GetString(ip, 0, strlen(ip)).Substring(7);

				return Encoding.ASCII.GetString(ip, 0, strlen(ip));
              		  } else {
				return String.Empty;
			}
		}
	}

        public int strlen(byte[] s)
        {
            if (s == null)
            {
                throw new ArgumentNullException();
            }

            int i;
            for (i = 0; i < s.Length && s[i] != 0; i++) ;
            return i;
        }`

**Comment by nxrighthere** [comment]
Thanks, I'll check it shortly.
