### ISSUE TITLE
Can Server instances have stricter timeout periods?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#32]
This is somewhat related to my transport as referenced in #28, but I suppose it's more "general".

What I wanted to know is if it's possible to set the server host to timeout any connection it's servicing if the connection in question hasn't responded within a configurable timeout.

I've noticed that when a client uncleanly disconnects from the server (as in, alt+f4) the behavior on the server is that the connection remains in a "connected" state for a while before eventually timing out. This timeout is like 15 to 30 seconds or even longer.

Ideally I'd like to have the server host object kill a connection that's not responding if it's "idle" for 5 seconds or longer. I know the client peer object allows one to specify timeouts on the connection via `Peer.timeout`, so if the server hasn't replied within X ~~seconds~~ ticks (?), the Peer will kill itself. However, that only seems to be on clients. I do know ENET-C# emits a Timeout/Disconnection event if a client does timeout, but the question on that is how do I configure the server-side timeout?

Or is that outside the realm of ENET's duties and up to the developer to implement such a system?

EDIT: Should be mentioned that I'm not talking about the `.Service(timeout, ...)` option as we can't do that since I'm using non-blocking service in a loop.

**Comment by wobes1** [comment]
```C#
var timeout = 5000;

peer.Timeout(ENet.Library.throttleScale, timeout, timeout * 5); // 5 seconds minimum, 25 seconds maximum

```
Call it on the server side on Connect event.

**Comment by nxrighthere** [comment]
As @wobes1 said, you set the timeout interval for a peer as soon as the connected event occurs. ENet disconnection logic is works differently, not like in the other libraries, to sustain packet loss and avoid unexpected disconnects even if the client has a poor network connection.
