### ISSUE TITLE
What's the maximum packet size that ENET can send?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#33]
Mirror HLAPI changed a few things in a [recent commit](https://github.com/vis2k/Mirror/commit/1289dee8b323247516053615f8eda33d350ee24d) and one of the changes was moving MaxPacketSize from Transport to TransportLayer in case some transports had maximum packet size restrictions. 

Do we have a per-packet data length limit that ENET imposes, or is it safe to return something like `int.MaxValue` or `uint.MaxValue` ?

Cheers!

**Comment by nxrighthere** [comment]
The maximum packet size is 33,554,432 bytes.

**Comment by nxrighthere** [comment]
Use this https://github.com/nxrighthere/ENet-CSharp/commit/11290f1980e00c751f58e827b6d6188124ddbb5b constant field.

**Comment by wobes1** [comment]
A bit of off top, could you reply to my comment Stanislav?
https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-miniudp-hazel-photon-and-others.512507/page-7#post-3895123
