### ISSUE TITLE
Peer provided by connect event is null on latest release

### ISSUE THREAD

**Issue by njbrown09** [nxrighthere/ENet-CSharp#35]
As the title says, the peer im receiving form the connect event on the server is null.

**Comment by nxrighthere** [comment]
`Peer` is a non-nullable struct, what do you mean? I've just checked it, and don't see any problems. Everything works as expected.

**Comment by nxrighthere** [comment]
You check if a peer is assigned or not using `Peer.IsSet` and compare them using their ID's. `Peer` doesn't inherit `IEquatable`.

**Comment by njbrown09** [comment]
Was an issue completely my fault unrelated to enet

**Comment by nxrighthere** [comment]
No problem. 😸
