### ISSUE TITLE
Connection Approval.

### ISSUE THREAD

**Issue by njbrown09** [nxrighthere/ENet-CSharp#36]
Is there any plans to add connection approval to enet? Its kind of a pain in the ass to do it on top of enet.

**Comment by nxrighthere** [comment]
It's a low-level networking library. Any high-level abstractions that should sit at application-level will not be implemented.

> Its kind of a pain in the ass to do it on top of enet.

I don't see any problem with that, in my application I've implemented that functionality for only a few lines of code, and instant connection rejection using `peer.DisconnectNow()`. Don't know what you are talking about.
