### ISSUE TITLE
What Version of ENet in the Packaged Releases?

### ISSUE THREAD

**Issue by crempp** [nxrighthere/ENet-CSharp#38]
I'm curious what version of ENet the packaged releases are using. I can't seem to figure it out on my own. The most recent version of ENet is 1.3.13 and I would like to know how far behind we are.

**Comment by nxrighthere** [comment]
Everything you need to know described in the readme, please read it carefully. This fork is an independent project which not tied to the original ENet, we freely modify it and move forward.

**Comment by crempp** [comment]
Ok, that makes sense and also explains why in my situation it's not communicating properly with another instance running the original ENet code. I'm guessing they're no longer using the same exact protocol.

Thanks

**Comment by nxrighthere** [comment]
Yep, the major 2.x.x version indicating that the protocol is no longer compatible with the original.
