### ISSUE TITLE
Not sure how to get peer by id

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#4]
Hi again, first I would like to say this library is amazing! I got way more done that I thought I could do tonight because it is so easy to use :).

There was one thing I couldn't figure out though, which was how do we get a peer by its id? I would like to send some packets to groups of specific peers and was wondering if there was a way to do that. I couldn't find it so I thought maybe I could store each Peer in a array as they connect to the server and then treat their position in the array as their id but I ran into an issue where apparently the type `netEvent.Peer` is different from the type `Peer `in my array.

I am going to sleep, so sorry if this is already documented somewhere; I couldn't find it but maybe i'm tired.

**Comment by bureto** [comment]
Haha nevermind I got it to work. I ended up making two separate arrays, one for the peerID and one for the peer. I'll probably tune it up later or find a better solution but for now this works :+1:

**Comment by nxrighthere** [comment]
You can do this even simpler using only one fixed array based on maximum connections + 1 slot to tell a newly connected peer that the server is full. Don't forget that you can put your custom data to the Peer.Data. So you can put there a position of that peer in the array, for example.

 >   netEvent.Peer is different from the type Peer in my array

They are the same. The Peer struct itself stores only a managed pointer to the peer from the native side. You can't compare them directly, but you can check assigned it or not using Peer.IsSet.

 >  Hi again, first I would like to say this library is amazing! I got way more done that I thought I could do tonight because it is so easy to use :).

I'm glad to hear that you like it.

**Comment by nxrighthere** [comment]
If you want I can add a function that will help you to get peer by ID from the unmanaged side.

**Comment by bureto** [comment]
No worries, I think it is working great :). I like the idea of storing the position of the peer in the array,  It definitely helped slim down on my code. Thanks :+1:

**Comment by bureto** [comment]
Sorry if this is off topic, but is there a way I can schedule to send packets a a specified frequency? I tried to create a looping coroutine for sending my movement packets but I think it is blocked by the 'game loop'. For now I am just sending them in Update() but I think it is sending way more than needed this way.

**Comment by nxrighthere** [comment]
It's logically should be blocked by game loop since you are sending movement updates. Sending the data within a specified interval in a game loop is fine.

Something like this:
```chsarp
private float nextUpdate = 0f;

private void Update() {
	if (Time.time > nextUpdate) {
		nextUpdate += 0.66f; // 15 messages per second

		// Send the position data
	}
}

**Comment by bureto** [comment]
Thank you. Sorry for raising so many issues too, after I see its a simple fix like this it makes me feel like a moron haha :) I'll quit bothering you (for a while) thanks man.

**Comment by njbrown09** [comment]
Bureto use a dictionary to store the peers.o

**Comment by bureto** [comment]
Thanks for the tip njbrown :). That sounds like it might be better. :+1:  I'll try that if I have any problems with the way I have it now.
