### ISSUE TITLE
Getting high latency

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#40]
Hi, sorry for bothering again.

Recently I have been having issues sending movement packets in my game. After a bit of trouble shooting, I came to the conclusion that I am probably misusing this library. 

Here is how I am sending the packets:
**Client to Server**

```
 public void sendPosition(Vector3 position, Vector3 rotation)
    {
        if (peer.State == PeerState.Connected)
        {
            ByteBuffer1 buffer = new ByteBuffer1();
            buffer.WriteByte(12);
            buffer.WriteVector3(position);
            buffer.WriteVector3(rotation);
            Packet packet = new Packet();
            byte[] data = buffer.ToArray();
            packet.Create(data, data.Length, PacketFlags.Unsequenced);
            peer.Send(3, ref packet);
            buffer.Dispose();
        }
    }
```
**Server to Client**
```
IEnumerator SendMovement(byte map, byte mode, int num)
    {
        while (true)
        {
            ByteBuffer1 buffer4 = new ByteBuffer1();
            buffer4.WriteByte(2);
            buffer4.WriteByte(lac.slots[map, mode, num]);
            for (int i = 0; i <= lac.slots[map, mode, num]; i++)
            {
                buffer4.WriteVector3(playerPosition[lac.id[map, mode, num, i]]); 
                buffer4.WriteVector3(playerRotation[lac.id[map, mode, num, i]]);
            }
            byte[] data = buffer4.ToArray();
            Packet packet = new Packet();
            packet.Create(data, data.Length, PacketFlags.Unsequenced);
            buffer4.Dispose();
            for (int i = 0; i <= lac.slots[map, mode, num]; i++)
            {
                peers[lac.id[map, mode, num, i]].Send(3, ref packet);
            }
            yield return new WaitForSeconds(0.1f);
        }
    }
```

It seems that the limit for my server (same thing happens on localhost) is as follows:

- 20 packets/s (2 clients @ 10 packets/s)
- roughly 600 bytes/s (my movement packets are 26 bytes each if you only count the stuff I put in it)

In the above scenario, my game runs fine; but as soon as I attempt a 4 player game (or two 2 player games), pretty much it is unusable  the ping goes up to 10000ms!

Here are my thoughts:

1. I checked the fps on my server and game client and it is at a constant 60+, so I believe it has to do with network congestion.
2. Since it is doing this on localHost, and 600 bytes/s is pretty low as well, something must be wrong with my code (not just crappy bandwidth)
3. Perhaps I am using the channel ID's wrong (maybe too many packets into channel 3), here is how I use them:
```
// NOTE: channel ids for sending packets goes as such:
//  0 for login stuff and initialization, stuff that can wait
//  1 for lobby functions, where latency is kinda important
//  2 for in game functions, important
//  3 for movement since we are sending alot of packets
```

edit:

I read your [conversation ](https://github.com/nxrighthere/ENet-CSharp/issues/27) with wobes1 and it cleared up my confusion about the channel id's. Since I am sending my movement packets as unsequenced-unreliable, it must not be them!

**Comment by bureto** [comment]
Just notices the bandwidth limit parameter, I am going to go and see if that's it. Just out of curiosity, what is the default value?

**Comment by nxrighthere** [comment]
This code doesn't tell me anything, I need a piece where you call the service, and process events, the most important job is done there.

**Comment by nxrighthere** [comment]
If you have questions that related to specifically to your high-level implementation, please join the [Discord](https://discord.gg/ceaWXVw), we can conveniently talk about it there, and I can help you to debug code via screen sharing.

**Comment by bureto** [comment]
First off, big thanks to all the people at the discord for helping to solve this issue!

Okay, before I begin I must say that I am running this on a single thread in the Unity game loop, and it is preferable to have your network running on a separate, designated thread;

The main thing that was causing this was the fact that Host.service was not called enough in the same frame. Here's how I had it: 

```
    private void Update()
    {
        Event netEvent;
        client.Service(0, out netEvent);
        switch (netEvent.Type)
        {
            case EventType.None:
                break;

            case EventType.Connect:
                Connect(netEvent);
                break;

            case EventType.Disconnect:
                break;

            case EventType.Timeout:
                Timeout(netEvent);
                break;

            case EventType.Receive:
                ProcessPacket(netEvent);
                break;
        }
    }
```
Here is the correct way to do it if you are running on the game loop on a single thread:
   ```
 private void Update()
    {
        bool nodata = false;
        do
        {
            Event netEvent;
            client.Service(0, out netEvent);
            switch (netEvent.Type)
            {
                case EventType.None:
                    nodata = true;
                    break;

                case EventType.Connect:
                    Connect(netEvent);
                    break;

                case EventType.Disconnect:
                    break;

                case EventType.Timeout:
                    Timeout(netEvent);
                    break;

                case EventType.Receive:
                    ProcessPacket(netEvent);
                    break;
            }
        } while (nodata == false);
    }
```
This way it can process multiple packets in the same frame! ( thx FSE_Vincenzo)

Another thing, you might want to use host.flush after queuing up your packets so that you can make sure they are all sent out. (thx nxrighthere)

If you are still having issues, you can also use PacketFlags.UnreliableFragment; (also thx nxrighthere)

Sorry I wish I could explain more, but all of this is thanks to the guys at Discord (there was a lot of people who helped).
I hope I didn't miss anything, this has been such a long process I can only account for the stuff we did today. I'm pretty sure that this will solve your issue if you had it similar to mine. Thanks again! :100:

**Comment by gamemachine** [comment]
Service returns 1 if an event was processed, so you can also just do if(client.Service(0, out netEvent) > 0).  That's what the Enet tutorial does actually.

**Comment by nxrighthere** [comment]
The best way to do this in your update cycle is:
```csharp
bool polled = false;

while (!polled) {
	if (server.CheckEvents(out netEvent) <= 0) {
		if (server.Service(timeout, out netEvent) <= 0)
			break;

		polled = true;
	}

	switch (netEvent.Type) {
		...
	}
}
```
