### ISSUE TITLE
Correct way of enabling compression?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#41]
I see that the library supports optional LZ4 compression. However, there is no documentation on when to use compression (as in, when to call the function to enable compression on the server or client). Do you call Host.EnableCompression() after you connect to the server on the client side? When do you call it on the server side when you want to create a compression-enabled server host object?

Cheers,
Coburn.

**Comment by nxrighthere** [comment]
Both sides can enable compression at any moment, but only after a host is created. If one of the sides didn't enable compression, then the appropriate packet will be dropped.

**Comment by SoftwareGuy** [comment]
Alright thanks. Just got it working with my custom built DLL. Appreciated.
