### ISSUE TITLE
Boolean check if Library is initialized

### ISSUE THREAD

**Issue by Agoxandr** [nxrighthere/ENet-CSharp#43]
Im not sure if this is possible but it would be nice to check if the library is done initializing. Maybe I missed something. If I don't wait enough time (2 - 5 seconds) I cant connect properly.

**Comment by nxrighthere** [comment]
https://github.com/nxrighthere/ENet-CSharp/blob/master/Source/Managed/ENet.cs#L800

**Comment by Agoxandr** [comment]
Thank you.
