### ISSUE TITLE
Strange MacOS Editor connection problems: Can't even connect to localhost.

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#46]
Hey NX,

This might be due to my implementation but going back a bit there was someone who had a similar issue (#24) to this but here goes. My issue ticket mainly to use as a bug marker is [located here](https://github.com/SoftwareGuy/Ignorance/issues/11) with the reproducible project.

It seems that if you have two Mac OS editors running on two copies of the same project, one in server mode on localhost port 7777 and one in client mode connecting to localhost on the same port, then you cannot connect the client mode instance to the server mode instance.

This seems to arise when I'm using it with the Mirror HLAPI integration, but here's the really weird part: Windows Editor instances works fine. You'd think that if macOS version of Unity had issues with the wrapper then it would be affect other operating systems, no? Well apparently not... this bug is only exclusive to macOS. 

I can't remember 100% but I do think that I can connect the macOS client to a Windows Editor host with no problems. And vice versa. Just that Mac OS localhost breaks itself.

Now, I know my code is not your project and I don't expect you to walk the full source code in the quest to squash this bug, but I would greatly appreciate you helping me look into this. I'm at my wits end without any ideas as to what could be going wrong - I'm currently thinking it's either something in Mac OS, or it's some quirk in ENET or ENET-C#. I'm not trying to point the finger at anyone here, but I've narrowed it down to 4 possibilities: Unity, my HLAPI integration, ENET-C# or the compiled ENET binary itself.

I'd gladly throw you some beer money if we can sort out this.

**Comment by nxrighthere** [comment]
Hi Cob.

> It seems that if you have two Mac OS editors running on two copies of the same project, one in server mode on localhost port 7777 and one in client mode connecting to localhost on the same port, then you cannot connect the client mode instance to the server mode instance.

Indeed some people in Discord faced the same problem on MacOS, and this was reproduced with a simple code, this is another Unity's editor bug, standalone is unaffected. Some guys said that the 2019 version works without a single problem, other people are reported that 2018 is buggy, I think all these bugs are related to the new .NET version and stuff around it. Unity is ignoring my last 3 bug reports for about a month that related to editor's bugs, so it's most likely that this will not be addressed by them.

> Now, I know my code is not your project and I don't expect you to walk the full source code in the quest to squash this bug, but I would greatly appreciate you helping me look into this.

Everything is alright.

**Comment by SoftwareGuy** [comment]
So you're confident that Unity Tech is shafting us with that issue since your bug reports are not being addressed by them refusing to answer your bug report/tickets? That's reassuring because it takes a lot of "what-if" possibilities off my mind.

I guess this could also be seen as a specific manifestation of my other older issue, while that one was "in general". I have to relay this to my user base as one of the users of Ignorance had to switch it out since it was giving him 100% failure rate.

Has there been any reports of ENET-C# working "without issue" on 2018.3? Or is the whole 2018 branch deemed "buggy"? Right now 2018.2.20 seems pretty alright sans for this issue. And I don't want to upgrade to an alpha version (looking at you, 2019.1).

Is there any other libraries you'd recommend that I could adapt for use in a HLAPI configuration that implement reliable UDP? I know LiteNetLib is one and I think I've seen you contributing bug fixes and/or advice to the developer of that said library. We've already got another developer bringing that to the Mirror Transport system.

Just a damn shame that we get jammed up on a damn Editor bug.

**Comment by nxrighthere** [comment]
> Has there been any reports of ENET-C# working "without issue" on 2018.3? Or is the whole 2018 branch deemed "buggy"? Right now 2018.2.20 seems pretty alright sans for this issue. And I don't want to upgrade to an alpha version (looking at you, 2019.1).

People in Discord including myself who work on Windows doesn't encounter any issues, for now. Linux headless servers are working stable as well (mine is running on AWS w/ Ubuntu). A few guys reported connection-related issues in the editor on MacOS, some minor weird things that related to Unity's Mono was fixed recently.

> Is there any other libraries you'd recommend that I could adapt for use in a HLAPI configuration that implement reliable UDP? I know LiteNetLib is one and I think I've seen you contributing bug fixes and/or advice to the developer of that said library. We've already got another developer bringing that to the Mirror Transport system.

I think only LiteNetLib is a viable choice, but you know, nothing is perfect and when such issues occur not much we can do on our side, unfortunately.

**Comment by nxrighthere** [comment]
This should be fixed in Unity 2019.1.0a14 and higher.

**Comment by SoftwareGuy** [comment]
Hey nx,

I just confirmed that I got it working two Editor Instances working with each other. This is Unity 2019.1.0b1 with Mirror and the ENET UDP Transport of mine:
![holy shit wtf man it worked 1](https://user-images.githubusercontent.com/1762115/52160114-7c43ac00-26fa-11e9-9d8f-ec5b5c2f5cf6.png)

However, there is a caveat here... Apparently IP Addresses, at least 127.0.0.1 has issues with whatever the heck is going on. If I bind the server to localhost in once instance, then connect to localhost in the client, it works fine. But if I try to manually connect to 127.0.0.1, it'll refuse to connect and time out.

I have no idea. But hey, at least we confirmed it works. For now, at least.

**Comment by nxrighthere** [comment]
And check if you bind to all interfaces (0.0.0.0 or ::0) connection to 127.0.0.1 works or not on Mac.

**Comment by SoftwareGuy** [comment]
Binding to `192.168.88.17` which is that boxes' IP LAN address and using the second Unity Editor to start connecting to it doesn't work, as it just gets stuck on Connecting.

Checking `0.0.0.0` now...

**Comment by SoftwareGuy** [comment]
`0.0.0.0` doesn't work either. However, out of curiosity since we're talking IP addresses I looked at my code where I bind the server instance to the IP address and commented it out just to test to see if there's a problem inside the SetHost call...

Sure enough, as soon as I did that and clicked "LAN Host" on the first client, it started the server, but when I tried `::1`, `127.0.0.1`, `localhost`, `192.168.88.17` on the client end - bingo. Every single attempt was successful - 100% rate.

Windows and Linux have been balls to the wall stable with this binding code - I can hear my workstation laughing and my Linux server pulling a trollface.jpg. I guess Mac wants to _network different_.

**Comment by nxrighthere** [comment]
Okay, about connecting to 127.0.0.1 if the host is bind to localhost on Linux/UNIX/POSIX. Unlike on the Windows it will be set by default to IPv6 address ::1, this is specified in the `/etc/hosts`. So here's two solutions:
1.  Make the following changes to `/etc/hosts`:
```
127.0.0.1    localhost
::1          localhost
```
2. Modify ENet to bind to both addresses when one of them is used for binding.

As for local 192.168.88.17 network address, the owner of this address should be your machine or you need to make sure that nothing prevents to connect to it, and the host was bind to it successfully.

**Comment by SoftwareGuy** [comment]
That's definitely the case, the `192.168.88.17` address is owned by the Mac box. My router, which is a MikroTik says that the MAC address in use for that IP matches the Mac's LAN MAC address.

Would you have to modify ENET's C language code to do that bind to both IPv4 and IPv6? Or would this be done in the C# layer? I hardly know any ANSI C, so I'd have to let you implement that.

**Comment by nxrighthere** [comment]
> Would you have to modify ENET's C language code to do that bind to both IPv4 and IPv6? Or would this be done in the C# layer? I hardly know any ANSI C, so I'd have to let you implement that.

I'm going to make a couple of tests before applying this changes, I'll comeback here soon.

**Comment by SoftwareGuy** [comment]
Sure - I look forward to your findings.

I'm gonna update my transport to remove the binding to IP code inside the Unity Editor, at least that seems to be broken only on Mac.

**Comment by nxrighthere** [comment]
Okay, if the ENet socket already bound to one of the interfaces it can't be bound additionally to another, so only the first option is the solution, however, binding to ::0 should work actually.

**Comment by SoftwareGuy** [comment]
Hmm, ok. Let me give that a shot and see if that makes any difference.

**Comment by nxrighthere** [comment]
Here's the simple test script which perfectly works on Windows and Linux:
```csharp
using System.Threading;
using System.Runtime.InteropServices;
using ENet;
using UnityEngine;

using Event = ENet.Event;
using EventType = ENet.EventType;

public class Test : MonoBehaviour {
	public int maxClients = 4;
	public ushort port = 9500;
	private volatile bool isAlive = true;
	private Thread serverThread;
	private Thread[] clientThreads;
	private byte[] data = new byte[64];
	private Peer[] clients;

	private void Start() {
		ENet.Library.Initialize();

		serverThread = new Thread(Server);
		serverThread.Start();

		clientThreads = new Thread[maxClients];

		for (int i = 0; i < maxClients; i++) {
			clientThreads[i] = new Thread(Client);
			clientThreads[i].Start();
		}

		clients = new Peer[maxClients];
	}

	private void SendPacket(Peer peer) {
		Packet packet = default(Packet);

		data[0] = 1;
		packet.Create(data, data.Length, PacketFlags.Reliable);
		peer.Send(0, ref packet);
	}

	private void Server() {
		using (Host server = new Host()) {
			Address address = new Address();

			address.Port = port;
			address.SetHost("::0");

			server.Create(address, maxClients, 2);

			Event netEvent;

			while (isAlive) {
				server.Service(15, out netEvent);

				switch (netEvent.Type) {
					case EventType.None:
						break;

					case EventType.Connect:
						Debug.Log("[Server] Client connected - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);

						clients[server.PeersCount - 1] = netEvent.Peer;

						if (server.PeersCount == maxClients) {
							Packet packet = default(Packet);

							data[0] = 2;
							packet.Create(data, data.Length, PacketFlags.Reliable);
							server.Broadcast(1, ref packet, clients);
						}
						break;

					case EventType.Disconnect:
						Debug.Log("[Server] Client disconnected - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);
						break;

					case EventType.Timeout:
						Debug.Log("[Server] Client timeout - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);
						break;

					case EventType.Receive:
						Debug.Log("[Server] Packet received from - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP + ", Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
						SendPacket(netEvent.Peer);
						Debug.Log("[Server] Packet sent to - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP + ", Data length: " + data.Length);
						netEvent.Packet.Dispose();
						break;
				}
			}

			server.Flush();
		}
	}

	private void Client() {
		using (Host client = new Host()) {
			Address address = new Address();

			address.SetHost("::1");
			address.Port = port;

			client.Create();

			Peer peer = client.Connect(address, 2);
			Event netEvent;

			while (isAlive) {
				client.Service(15, out netEvent);

				switch (netEvent.Type) {
					case EventType.None:
						break;

					case EventType.Connect:
						Debug.Log("[Client] Client connected to server - ID: " + peer.ID);
						SendPacket(peer);
						Debug.Log("[Client] Packet sent to server - Data length: " + data.Length);
						break;

					case EventType.Disconnect:
						Debug.Log("[Client] Client disconnected from server");
						break;

					case EventType.Timeout:
						Debug.Log("[Client] Client connection timeout");
						break;

					case EventType.Receive:
						if (Marshal.ReadByte(netEvent.Packet.Data, 0) == 1)
							Debug.Log("[Client] Packet received from server - Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
						else if (Marshal.ReadByte(netEvent.Packet.Data, 0) == 2)
							Debug.Log("[Client] Broadcasted packet received from server - Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
						
						netEvent.Packet.Dispose();					
						break;
				}
			}

			client.Flush();
		}
	}

	private void OnDestroy() {
		isAlive = false;
		ENet.Library.Deinitialize();
	}
}
```

**Comment by SoftwareGuy** [comment]
Thanks for the sample code - I'll file it away under references. 😄 

Just patched the `::0` into my transport code, and it's working as intended. Tested another editor instance using localhost, the box network IP (192.168.x.x), `::1` and `127.0.0.1` with 100% success rate for all connections.

So I think I will need to document that in my transport and if they click LAN Host on OS X I will just bind to `::0`. On Windows and Linux I will offer the "bind to IP" function which has some use on servers with more than one static IP. I know you could use `iptables` trickery but eh.

I'll keep in touch and see if this problem occurs again, but thanks very much - I am relieved that we were able to identify it down to a Mac OS oddity.
