### ISSUE TITLE
unused memory in enet_packet_create_offset malloc?

### ISSUE THREAD

**Issue by kersk** [nxrighthere/ENet-CSharp#48]
https://github.com/nxrighthere/ENet-CSharp/blob/8c368baa9ed9661d68a27ab9f1ccd1238923e5b6/Source/Native/enet.h#L1159

Should this just be:
`packet = (ENetPacket*)enet_malloc(sizeof(ENetPacket) + dataLength); `

?

**Comment by kersk** [comment]
if (ENET_PACKET_FLAG_NO_ALLOCATE)
    packet->data = (enet_uint8 *)data + dataOffset;

and

packet->dataLength   = dataLength;

 as well?

**Comment by nxrighthere** [comment]
This function actually serves to add offset for custom packet headers rather than slice some bytes from it. I'll change this behavior...
