### ISSUE TITLE
Clarification regarding PeerLimit parameter on the Host object

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#50]
Just need some clarification regarding peerLimit parameter when creating the Host.

Does peerLimit operate like this (probably bad) example? Say if we set it to 1000, then there's 1000 lottery tickets. Each peer that connects takes a lottery ticket, and the pool of lottery tickets becomes 999 and so on. When the 1000 tickets are exhausted, it will refuse any new connections.

The reason I ask is because initially I thought that it was a limit on how many peers can connect at one given time (max CCUs, not max connection count), but it seems that this is a hard cap of how many peer connections can actually take place. I originally had peerLimit set to Mirror's maximum connections limit (which defaults to 4). However on the 5th connection it would just silently reject the connection.

I know it might be ethical to cap a servers connections count to prevent connection spammers connecting to the port, trying to dump data and then disconnect.

Am I on the money or do you have a better explaination? Could this be clarified in the documentation (as in, this is not a CCU limit, but how many connections globally until the server refuses extra ones)?

**Comment by nxrighthere** [comment]
UDP is connectionless protocol if you don't reserve one slot to instantly reject a connection when the actual limit was reached using for example, `DisconnectionNow(Reason.ServerIsFull)` with an appropriate event code, then the connection will be just timed out.
