### ISSUE TITLE
Compiling ENET with Debug Symbols?

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#51]
Hey nx,

Someone managed to crash the ENET Native Library while they were using a stable release of my Transport ([see here](https://github.com/SoftwareGuy/Ignorance/issues/20)) and was wondering if I could compile a version of ENET that had debugging symbols enabled so they could debug further.

I noticed in the C code that there's calls to a definition of ENET_DEBUG but there's no CMake option for that. So I manually tried adding it into the CMakeLists and rebuilding the cache, and that ENET_DEBUG option appeared when in `ccmake` for interactive configuration, but it didn't seem to do anything (I can't remember if it bulked up the DLL it spat out).

Could you make a debug option available for this sort of debugging processes?

**Comment by nxrighthere** [comment]
There's nothing to do with complication directives, compile debug version using your toolchain.

If the crashed was caused by ENet module, then you will find the appropriate stack trace in the log files of the editor.

**Comment by GabeBigBoxVR** [comment]
Here's the stack that I got, I think the issue might be in ENet that it's trying to receive a packet despite an immediate disconnect request.

```0x00000000653A149F (enet) enet_linked_version
0x00000000653A1CC8 (enet) enet_peer_receive
0x00000000653A49FF (enet) enet_peer_disconnect_now
0x0000029DA06DA8CD (Mono JIT Code) (wrapper managed-to-native) ENet.Native:enet_peer_disconnect_now (intptr,uint)
0x0000029DA06DA82B (Mono JIT Code) ENet.Peer:DisconnectNow (uint)
0x0000029DA0694B6B (Mono JIT Code) Mirror.IgnoranceTransport:ClientDisconnect ()
0x0000029DA06949D0 (Mono JIT Code) Mirror.NetworkConnection:Disconnect ()
0x0000029DA06948A3 (Mono JIT Code) Mirror.NetworkServer:DisconnectAllConnections ()
0x0000029DA069474B (Mono JIT Code) Mirror.NetworkServer:DisconnectAll ()
0x0000029DA069445B (Mono JIT Code) Mirror.NetworkServer:Shutdown ()
0x0000029DA069435B (Mono JIT Code) Mirror.NetworkManager:StopServer ()
0x0000029DA069425B (Mono JIT Code) Mirror.NetworkManager:StopHost ()
0x0000029DA06941DB (Mono JIT Code) NetworkingHost:ConnectToServerOnSceneChange (ServerDiscoveryRecord)
0x0000029DA0694093 (Mono JIT Code) TestRoomShuttle:Connect ()
0x0000029DF84C6AD0 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FF8A17DBE4B (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FF8A1761E32 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FF8A176AE3F (mono-2.0-bdwgc) mono_runtime_invoke
0x00007FF887B15C64 (UnityPlayer) scripting_method_invoke
0x00007FF887B13490 (UnityPlayer) ScriptingInvocation::Invoke
0x00007FF887B1354E (UnityPlayer) ScriptingInvocation::InvokeChecked
0x00007FF887AFFD76 (UnityPlayer) MonoBehaviour::CallMethodInactive
0x00007FF887AFFCC8 (UnityPlayer) MonoBehaviour::CallMethodInactive
0x00007FF887B10DF5 (UnityPlayer) ForwardInvokeDelayed
0x00007FF8878F4FB2 (UnityPlayer) DelayedCallManager::Update
0x00007FF887A205F7 (UnityPlayer) ExecutePlayerLoop
0x00007FF887A20699 (UnityPlayer) ExecutePlayerLoop
0x00007FF887A2261F (UnityPlayer) PlayerLoop
0x00007FF8877FBD25 (UnityPlayer) PerformMainLoop
0x00007FF8877FA66A (UnityPlayer) MainMessageLoop
0x00007FF8877FF0EA (UnityPlayer) UnityMainImpl
0x00007FF88780320B (UnityPlayer) UnityMain
0x00007FF7074A11FA (PopulationONE) __scrt_common_main_seh
0x00007FF8EB4E3034 (KERNEL32) BaseThreadInitThunk
0x00007FF8EC7D3691 (ntdll) RtlUserThreadStart```

**Comment by nxrighthere** [comment]
No, the problem is in the code on top, as soon as `peer.DisconnectNow` is called the host is flushed, and all internal queues are reset.

The function is called from the same thread where ENet lives? At which moment do you call the disconnect exactly? Can you send the dump to my email?

**Comment by nxrighthere** [comment]
I don't see how this crash can occur in the normal code, it most likely that thread-safety on top is not preserved, and memory was corrupted.
