### ISSUE TITLE
How to connect to the server on Android

### ISSUE THREAD

**Issue by qiqiqidalao** [nxrighthere/ENet-CSharp#58]
I put libenet.so in the corresponding folder of Unity, package it into apk and use mlogcat to view the Android debug log. The Service method in ENet.cs always returns 0, which makes it impossible to connect to the server.

`var result = Native.enet_host_service(nativeHost, out nativeEvent, (uint)timeout);`

Obviously, the method in .so is called, but I don't know where it went wrong.

**Comment by nxrighthere** [comment]
Without the code I can't help you. [This](https://github.com/nxrighthere/ENet-CSharp/issues/46#issuecomment-459942567) example works fine for me on Android.

**Comment by qiqiqidalao** [comment]
This is client code
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ENet;

namespace MOBA_CSharp_Client.ClientNetwork
{
    public delegate void MessageHandler(byte[] data);

    class ClientNetwork
    {
        MessageHandler[] handlers;

        Host client;
        Address address;
        Peer peer;

        public ClientNetwork()
        {
            handlers = new MessageHandler[Enum.GetNames(typeof(MessageType)).Length];
        }

        public void SetMessageHandler(MessageType type, MessageHandler handler)
        {
            handlers[(int)type] = handler;
        }

        public void ClearMessageHandlers()
        {
            for(int i=0; i<handlers.Length; i++)
            {
                handlers[i] = null;
            }
        }

        public void Connect(string hostName, ushort port)
        {
            Library.Initialize();

            client = new Host();

            address = new Address();
            address.SetHost(hostName);
            address.Port = port;

            client.Create();

            peer = client.Connect(address);
        }

        public void Shutdown()
        {
            if (client != null)
            {
                client.Flush();
                peer.DisconnectNow(0);
                Library.Deinitialize();
            }
        }

        public void Service()
        {
            Event netEvent;
            while (client.Service(0, out netEvent) > 0)
            {
                switch (netEvent.Type)
                {
                    case EventType.None:
                        break;

                    case EventType.Connect:
                        Console.WriteLine("Client connected to server - ID: " + peer.ID);
                        Invoke(MessageType.Connect, new byte[0]);
                        break;

                    case EventType.Disconnect:
                        Console.WriteLine("Client disconnected from server");
                        Invoke(MessageType.Disconnect, new byte[0]);
                        break;

                    case EventType.Timeout:
                        Console.WriteLine("Client connection timeout");
                        Invoke(MessageType.Timeout, new byte[0]);
                        break;

                    case EventType.Receive:
                        Console.WriteLine("Packet received from server - Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
                        Receive(netEvent);
                        netEvent.Packet.Dispose();
                        break;
                }
            }
        }

        void Invoke(MessageType type, byte[] data)
        {
            handlers[(int)type]?.Invoke(data);
        }

        void Receive(Event netEvent)
        {
            if(netEvent.Packet.Length < MessageConfig.MESSAGE_LEN)
            {
                return;
            }

            byte[] buffer = new byte[netEvent.Packet.Length];
            netEvent.Packet.CopyTo(buffer);

            MessageType type = (MessageType)BitConverter.ToInt16(buffer, 0);

            byte[] data = new byte[netEvent.Packet.Length - MessageConfig.MESSAGE_LEN];
            Array.Copy(buffer, 2, data, 0, data.Length);

            Invoke(type, data);
        }

        public void Send(MessageType type, byte[] data, PacketFlags flags)
        {
            Packet packet = default(Packet);
            byte[] buffer = new byte[MessageConfig.MESSAGE_LEN + data.Length];

            byte[] byteType = BitConverter.GetBytes((ushort)type);
            Array.Copy(byteType, buffer, MessageConfig.MESSAGE_LEN);

            Array.Copy(data, 0, buffer, MessageConfig.MESSAGE_LEN, data.Length);

            packet.Create(buffer, flags);
            peer.Send(0, ref packet);
        }

        public uint GetPeerID()
        {
            return peer.ID;
        }
    }
}
`
And the PeerID printed on mlogcat is a negative value.

**Comment by qiqiqidalao** [comment]
Using the released version of the libenet.so file will report the exception of enet not found, so I rebuilt a libenet.so with the .c and .h you provided.

[libs.zip](https://github.com/nxrighthere/ENet-CSharp/files/3017172/libs.zip)
This is my refactored libenet.so tarball

**Comment by nxrighthere** [comment]
The library that I provided is intended to use for the desktop platform as mentioned in the readme, not for mobiles. You need to build ENet using NDK and assign all compiled libraries to appropriate platforms and CPU architectures in Unity, otherwise, it will not work correctly.

The service function should be called continuously on both sides during the lifetime of the application.

**Comment by qiqiqidalao** [comment]
I have refactored enet.c and enet.h in the Native folder of ENet-CSharp-2.2.2.zip, and put the refactored libenet.so under Assets/Plugins/Andriod/libs, but the phone Still unable to connect to the server.

**Comment by nxrighthere** [comment]
[This](https://github.com/nxrighthere/ENet-CSharp/issues/46#issuecomment-459942567) example works fine for you? Just build a single executable and run it on your device. If the test will be done successfully the application will self-terminate.

**Comment by qiqiqidalao** [comment]
t didn't seem to be a success. I created a new project and mounted the script on an empty object and imported the file in Enet-Unity-2.2.2.zip. Running the script on the Windows platform causes Unity to crash, and on the Android platform, it reports an exception of enet not found.
