### ISSUE TITLE
Server gets stuck on Receive after sometime

### ISSUE THREAD

**Issue by tzurE** [nxrighthere/ENet-CSharp#59]
Hi, I've encountered a problem which I can't seem to solve. It doesn't happen all the time, but some of the time. I'll explain the overall arch of my server, and try to pinpoint to exact location I believe is the problem.

So, I have a **server** which opens a thread for receiving events. It's pretty straightforward - very similar to your example:
First of all, I call "Listen" on my main thread:

    `public void Listen(ushort port, int peerLimit)
        {
            ENet.Library.Initialize();
            server = new Host();
            address = new Address();
            address.Port = port;
            server.Create(address, peerLimit);
        }`

Then, on my other thread, I call "Start"

    `public void Start()
        {
            Event netEvent;
            while (!shutdown) {
                bool polled = false;
                while (!polled) {
                    if (server.CheckEvents(out netEvent) <= 0) {
                        if (server.Service(0, out netEvent) <= 0)
                            break;

                        polled = true;
                    }
                    switch (netEvent.Type) {
                        case EventType.None:
                            break;

                        case EventType.Connect:
                            Console.WriteLine("Client connected - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);
                            Console.WriteLine(DateTime.Now.Millisecond.ToString());
                            break;

                        case EventType.Disconnect:
                            Console.WriteLine("Client disconnected - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);                       
                            disconnectedClientQueue.Enqueue(netEvent.Peer.ID);
                            break;

                        case EventType.Timeout:
                            Console.WriteLine("Client timeout - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP);
                            disconnectedClientQueue.Enqueue(netEvent.Peer.ID);                            
                            break;

                        case EventType.Receive:
                            Console.WriteLine("Packet received from - ID: " + netEvent.Peer.ID + ", IP: " + netEvent.Peer.IP + ", Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
                            var p = new ReceiveEventPacket{
                                packet = netEvent.Packet,
                                channel = netEvent.ChannelID,
                                peerId = netEvent.Peer.ID
                            };
                            EnetEventPacketQueue.Enqueue(p);
                            break;
                    }
                }
            }
            server.Flush();
        }`

Server works fine at the start. I have a client who has the same configuration - a thread for listening to incoming packtes/events, and a main thread to send stuff.
Client connects on main thread:

    `public void Connect(string hostName, ushort port)
        {
            ENet.Library.Initialize();
            client = new Host();

            address = new Address();
            address.SetHost(hostName);
            address.Port = port;
            client.Create();
            peer = client.Connect(address); 
        }`
Then on my second thread, it listens for incoming connections

    `        public void Start() {
            Event netEvent;

            while (!Console.KeyAvailable && !shutdown) {
                bool polled = false;
                while (!polled) {
                    if (client.CheckEvents(out netEvent) <= 0) {
                        if (client.Service(0, out netEvent) <= 0)
                            break;

                        polled = true;
                    }

                    switch (netEvent.Type) {
                        case EventType.None:
                            break;

                        case EventType.Connect:
                            Console.WriteLine("Client connected to server - ID: " + peer.ID);
                            Console.WriteLine(DateTime.Now.Millisecond.ToString());
                            break;

                        case EventType.Disconnect:
                            Console.WriteLine("Client disconnected from server");
                            Console.WriteLine("Press any key to close");
                            this.shutdown = true;
                            break;

                        case EventType.Timeout:
                            Console.WriteLine("Client connection timeout");
                            this.shutdown = true;
                            break;

                        case EventType.Receive:
                            //Console.WriteLine("Packet received from server - Channel ID: " + netEvent.ChannelID + ", Data length: " + netEvent.Packet.Length);
                            // if (netEvent.Peer.ID == peer.ID){
                            //     netEvent.Packet.Dispose();
                            //     break;
                            // }
                            var p = new ReceiveEventPacket{
                                packet = netEvent.Packet,
                                channel = netEvent.ChannelID,
                                peerId = netEvent.Peer.ID
                            };
                            EnetEventPacketQueue.Enqueue(p);
                            // move the Receive to a different thread - dequeue
                            //Receive(netEvent);
                            //netEvent.Packet.Dispose();
                            break;
                    }
                }
            }
            peer.DisconnectNow(0);
            client.Flush();
            Console.WriteLine("Shuttding down Client");
            ENet.Library.Deinitialize();
        }`

It works well at the start, the server receives my packets and everything works great.
I'm using a [ringbuffer](https://github.com/dave-hillier/disruptor-unity3d/tree/master/DisruptorUnity3d) for thread safe stuff - my secondary thread enqueues new packets, and my main thread dequeues them and the game state gets updated. The main thread also sends updates on my world state (creates a new packet, and sends it using Broadcast, but only after it finished the dequeue of the received packets).
My problem is that sometimes, the server just **stops** receiving packets. I ran my server in Debug mode and took a good look at my threads. My main thread works great - it keeps enqueueing packets and all.
My other thread gets stuck on the
    `Service(0, out netEvent)`
line.
Attached is an image of that moment in debug mode:
![image](https://user-images.githubusercontent.com/7524039/55237043-46c2c700-5242-11e9-889e-007e998b683d.png)

I can see my main thread running, my client sending packets (it prints out each time a packet is sent) but my server refuses to acknowledge that. It simply ignores my packets altogether and just gets stuck.
I'm pretty lost, I have no idea what I'm doing wrong. The ringbuffer example was something I took directly from someone who helped me here, and it seems to be working. But it seems like my server keeps waiting for packets - and they never come.
I canceled every firewall on the way(it's localhost anyway), and I'm trying to use Wireshark to understand where my packets are going, but I'm really not sure.

Have you ever encountered something like that before? Can you please provide some information? maybe I'm missing something here?

**Comment by nxrighthere** [comment]
> Then on my second thread, it listens for incoming connections
You violated thread-safety with this. You can't have two separated threads using the service simultaneously without synchronizing mechanism. There should be only one thread that does all stuff around the service.

**Comment by nxrighthere** [comment]
And by the way, if your thread doesn't have a slight timeout/sleep, it will eat your CPU power.

**Comment by nxrighthere** [comment]
[Here's](https://github.com/nxrighthere/ENet-CSharp/issues/46#issuecomment-459942567) a proper example of how it should be done.

**Comment by nxrighthere** [comment]
[Here's](https://github.com/rthompsonj/EnetPrototype) a bit outdated prototype which you can use as an example.

**Comment by tzurE** [comment]
Wait, so, using Broadcast is what breaks it?
Because my main thread does not listen to incoming connections, it simply dequeues packets received from the secondary thread(which is the one listening) and handles them. it also uses Broadcast, but that's it. Service is being called from only one thread.

**Comment by tzurE** [comment]
oh, wait - you're saying the Client is what is breaking everything?

**Comment by nxrighthere** [comment]
Can you send me your full project?

**Comment by tzurE** [comment]
No need! Moving the Broadcast to the main thread that runs the Service() solved it!
Thank you!

**Comment by tzurE** [comment]
@nxrighthere , if we're already here - can you explain the changes regarding the ID? now my server starts at 0, but every time I connect a new client - the server increments it, but the client keeps getting peer(local) id of 0.
server side - 

    `Server Started
    Client connected - ID: 0, IP: 127.0.0.1
    Packet received from - ID: 0, IP: 127.0.0.1, Channel ID: 0, Data length: 52
    Entity with id: 0 current location: 0,0.257,0 current velocity: 0,0,0 rotation:0,0,0 HP: 100
    Client connected - ID: 1, IP: 127.0.0.1
    Packet received from - ID: 1, IP: 127.0.0.1, Channel ID: 0, Data length: 52
    Client disconnected - ID: 1, IP: 127.0.0.1`

Client 1 side:
    `Client connected to server - ID: 0
    Client connected.`

client 2 side:
 
    `Client connected to server - ID: 0
    Client connected.`
