### ISSUE TITLE
How to simulate latency?

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#6]
Hi, so previously I was simulating lag by putting a delay before I sent the packet to the server (or server sent to client). This was okay but now I need a way for it to affect the `Peer.RoundTripTime` . Is there a easy way to do that? Thanks again.

**Comment by nxrighthere** [comment]
Use [Clumsy](http://jagt.github.io/clumsy/) or any other similar tool to simulate bad network conditions.
