### ISSUE TITLE
System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

### ISSUE THREAD

**Issue by solsahar** [nxrighthere/ENet-CSharp#60]
I am getting a error : System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

The code that is triggering the error is :

Address address = new Address();
address.Port = 8888;
server.Create(address, 30);

**Comment by nxrighthere** [comment]
You are using the managed assembly which is incompatible with your runtime.

**Comment by nxrighthere** [comment]
Grab the appropriate version from NuGet package or [compile it](https://github.com/nxrighthere/ENet-CSharp/tree/master/Source/Managed) yourself using your toolchain.

**Comment by AnImperialMan** [comment]
I got same error here:
ENet.Library.Initialize(); 

I'm using the latest NuGet Package. MonoGame for Desktop, launch it in LoadContent

**Comment by nxrighthere** [comment]
The NuGet package contains compiled x64 assembly for .NET Framework 3.5+, .NET Core 2.0+, .NET Standard 2.0+.

**Comment by AnImperialMan** [comment]
thx, it worked.
