### ISSUE TITLE
Method's type signature is not PInvoke compatible

### ISSUE THREAD

**Issue by ryanxia2016** [nxrighthere/ENet-CSharp#8]
using release v2.0.4's enet.dll with latest code in github.

The sample server seemed started and listening .
but when connect event fired, a Exception thrown out:

 Method's type signature is not PInvoke compatible. 
 at ENet.Native.enet_peer_get_address(IntPtr peer)

**Comment by nxrighthere** [comment]
What operating system you running on/scripting backend?

**Comment by ryanxia2016** [comment]
Windows 10 Pro / net core 2.1

**Comment by ryanxia2016** [comment]
here it is
[TestENetServer.zip](https://github.com/nxrighthere/ENet-CSharp/files/2321590/TestENetServer.zip)

**Comment by nxrighthere** [comment]
Funny, but it seems that the .NET Core for some reason can't marshal Address struct like .NET Framework. I'll try to fix it and then fill a bug report in the .NET Core repository.

By the way, don't use `SpinWait` with `SpinOnce` in the loop, it's not needed.

**Comment by nxrighthere** [comment]
You can track a bug report here https://github.com/dotnet/coreclr/issues/19676

**Comment by ryanxia2016** [comment]
thanks.
I will keep following.

**Comment by nxrighthere** [comment]
I'm working on a workaround for this issue, so stay tuned.

**Comment by ryanxia2016** [comment]
looking forward to it.

**Comment by nxrighthere** [comment]
It fixed in [2.0.5 version](https://github.com/nxrighthere/ENet-CSharp/releases) with https://github.com/nxrighthere/ENet-CSharp/commit/d7615a3c200db95ad52ac37bfb6bc6908807c5ae commit. An API is slightly [changed](https://github.com/nxrighthere/ENet-CSharp/commit/dbcb94e22437e443491994a038f931216fc43bbe) so don't forget to change stuff in your code.

Let me know how it works for you.

**Comment by ryanxia2016** [comment]
I will try it soon.
now can not get client port with peer?

**Comment by nxrighthere** [comment]
The port number specified on the server side will always be the same for the clients.

**Comment by ryanxia2016** [comment]
client should have a local port opened, some time the client's local port is useful.

and, now, connect event is fired OK, but EventType.Receive is not fired ( No Exception, just nothing happpen after client send messages)

**Comment by nxrighthere** [comment]
> client should have a local port opened, some time the client's local port is useful.

If you are talking about the port number for NAT traversal, this has nothing to do with ENet.

> but EventType.Receive is never fired ( No Exception, just nothing happen after client send messages)

It works fine for me. Check your code carefully.

**Comment by nxrighthere** [comment]
> client should have a local port opened, some time the client's local port is useful.

You are talking about the port number that assigned by the OS?
