### ISSUE TITLE
enet.dll caused an Access Violation (0xc0000005)

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#9]
Hi again, I am hoping someone might know what this means.

```
enet.dll caused an Access Violation (0xc0000005)
  in module enet.dll at 0033:66a0643a.

Error occurred at 2018-08-26_155236.
E:\Program Files\Unity\Editor\Unity.exe, run by Bureto.
39% memory in use.
16284 MB physical memory [9806 MB free].
32566 MB paging file [24615 MB free].
8388608 MB user address space [8386493 MB free].
Read from location 00000038 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x00000000  RAX:   0x00000000
RBX:    0x44ad5640  RCX: 0x00000000  RDX:   0x080500d0
RIP:    0x66a0643a  RBP: 0x0022d580  SegCs: 0x00000033
EFlags: 0x00010246  RSP: 0x0022d580  SegSs: 0x0000002b
R8:    0x0022d248  R9: 0x00000011  R10:   0x00000001
R11:    0x66a0642e  R12: 0x00000001  R13:   0x00000000
R14:    0x16038760  R15: 0x00000000

Bytes at CS:EIP:
48 8b 40 38 5d c3 55 48 89 e5 48 89 4d 10 48 89 
```
This is the short version of the log, I can post full log details (long) if it is necessary.

On my server, it is giving me this error right when the player connects. The library was working on my 'test' server but when I went and put it on my real game server it crashed.

 So far I haven't found a solution, any ideas and help appreciated. Thanks

**Comment by nxrighthere** [comment]
Attach zip archive with the project to comment or send it to my [email](mailto:nxrighthere@gmail.com). I can't help without looking into the source code.

**Comment by bureto** [comment]
It's okay I just found it :). `if(peers[i].Data == IntPtr.Zero)` was apparently the issue. Sorry for not uploading code at first I didn't know where it was at first.

I was using `if(peers[i].Data == IntPtr.Zero)` to check and see if the peer was assigned in array, since I assign it's position in array in the `Data`. I was assuming that IntPtr.Zero was default value but I guess it just causes issues. Guess I am gonna figure out what else I can do instead. If you have any ideas please let me know, thanks again. :+1:

**Comment by nxrighthere** [comment]
With PInvoke `IntPtr.Zero` means `NULL`. You should use a cast of data type instead.

For example:
`if (peers[i].Data == (IntPtr)(-1))`

Assigning a value with position in the array:
`peer.Data = (IntPtr)i;`

Remove the position from the array,
`peer.Data = (IntPtr)(-1);`

I think I should add a check on `IntPtr.Zero` across the wrapper.

**Comment by bureto** [comment]
Hi thanks for the good idea. :) So when I create the array I should do something like this:
```
for(int i = 0; i < peers.Length; i++)
{
    peers[i].Data = (IntPtr)(-1);
}
```
To set the default value, right?

**Comment by nxrighthere** [comment]
Yep.

**Comment by bureto** [comment]
```
 void Start()
    {
        ENet.Library.Initialize();
        StartServer();
        outputText.text = "Server started";
    }

    private void StartServer()
    {
        for (int i = 0; i < peers.Length; i++)
        {
            // Set default value of peer data to -1
            peers[i].Data = (IntPtr)(-1);
        }
        server = new Host();
        address = new Address();
        address.Port = port;
        server.Create(address, maxClients);
    }

```

Still crashing, this time from using `            peers[i].Data = (IntPtr)(-1);`
Am i doing it right haha

**Comment by nxrighthere** [comment]
```csharp
for (int i = 0; i < peers.Length; i++) {
    // Set default value of peer data to -1
    peers[i].Data = (IntPtr)(-1);
}
```
You can't assign the data to an unassigned peer.

I edited my  previous post, please take a look.

**Comment by nxrighthere** [comment]
I'm going to add some internal checks to the wrapper to avoid this issues.

**Comment by nxrighthere** [comment]
No problem, if you have some questions feel free to ask.

**Comment by nxrighthere** [comment]
After this https://github.com/nxrighthere/ENet-CSharp/commit/c76875d1e69b2d66533322eb7db1c94985aa1bfb change you should notice where thing are going wrong.

**Comment by bureto** [comment]
Thanks! That looks very helpful for me I will definitely download the new updated version in the morning.
